name: Github Action with Nginx, K8s and Load Balancer

on:
    pull_request: 
        types: [closed]
        branches: 
            - main

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to Docker Registry
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PASS }}
            - name: Build Image
              run: |
                echo "Directory before moving: $(pwd)"
                cd projects/github-actions
                echo "Current Directory: $(pwd)"
                docker build -t mynix:latest .
            - name: Test
              run: |
                docker run -d -p 8080:80 --name mynix mynix:latest
                sleep 5
                docker ps -a
                curl -k http://localhost:8080 | grep "Hello from GitHub Actions"
                docker stop mynix
            - name: docker push
              run: |
                docker tag mynix:test ${{ secrets.DOCKER_USER }}/mynix:latest
                docker push ${{ secrets.DOCKER_USER }}/mynix:latest
            

